package magic.logic.utils;

public enum AGMEvent implements GameEvent {

	UNTIL_END_OF_TURN, UNTIL_CARD_LEAVE_BATTLEFIELD, GLOBAL_UNTIL_CARD_LEAVE_BATTLEFIELD,
	
	ADD_GLOBAL_EFFECT, REMOVE_GLOBAL_EFFECT, ADD_TO_GLOBAL,

	SHUFFLE_LIBRARY,
	
	REMOVE_FROM_PILE,
	
	SET_LIFE,
	
	SEND_CARD, SEND_DECK,
	
	TRANSFORM,

	ADD_CAPACITIES, REMOVE_CAPACITIES,
	
	ADD_CARD_TYPE, REMOVE_CARD_TYPE,
	
	ADD_CREATURE_TYPE, REMOVE_CREATURE_TYPE,
	
	ADD_ABILITIES, REMOVE_ABILITIES,

	ADD_STAT, REMOVE_STAT;
}
