package magic.logic.card.abilities;

public enum Capacities {
	DEATHTOUCH, DEFENDER, DOUBLE_STRIKE, FIRST_STRIKE, FLYING, HASTE, HEXPROOF, INDESTRUCTIBLE, LIFELINK, MENACE, REACH,
	TRAMPLE, VIGILANCE, SHROUD;
}
