package magic.logic.card.abilities;

public enum Interdiction {
	BLOCK, BE_BLOCKED, ATTACK, ACTIVATE_ABILITY, BE_COUNTERED, BE_REGENERATED, BE_THE_TARGET, BE_EQUIPPED, BE_ENCHANTED,
	GAIN_LIFE, GAIN, CAST, PLAY, WIN_GAME, LOSE_GAME, DAMAGE_BE_PREVENTED, SEARCH_LIBRARIES, PUT_COUNTERS, DRAW_CARDS,
	UNTAP, DEALT_DAMAGE;
}
