package magic.logic.card.abilities.utils;

public enum CounterType {

    ALL_COUNTER, PLUS_ONE, MINUS_ONE, ACORN, AGE, AIM, ARROW, ARROWHEAD, AWAKENING, BLAZE, BLOOD, BOUNTY, BRIBERY,
    BRICK, CAGE, CARRION, CHARGE, COIN, CREDIT, CORPSE, CRYSTAL, CUBE, CURRENCY, DEATH, DEATHTOUCH, DELAY, DEPLETION,
    DESPAIR, DEVOTION, DIVINITY, DOOM, DOUBLE_STRIKE, DREAM, ECHO, EGG, ELIXIR, ENERGY, EON, EXPERIENCE, EYEBALL,
    EYESTALK, FADE, FATE, FEATHER, FETCH, FILIBUSTER, FIRST_STRIKE, FLYING, FUNGUS, FUSE, GEM, GLYPH, GOLD, GROWTH,
    HASTE, HATCHLING, HEALING, HEXPROOF, HIT, HOOFPRINT, HOUT, HOURGLASS, HUNGER, ICE, INCUBATION, INDESTRUCTIBLE,
    INFECTION, INTERVENTION, ISOLATION, JAVELIN, KI, KNOWLEDGE, LEVEL, LIFELINK, LORE, LOYALTY, LUCK, MAGNET, MANABOND,
    MANIFESTATION, MANNEQUIN, MASK, MATRIX, MENACE, MINE, MINING, MIRE, MUSIC, MUSTER, NET, OMEN, ORE, PAGE, PAIN,
    PARALYZATION, PETAL, PETRIFICATION, PHYLACTERY, PIN, PLAGUE, POISON, POLYP, PRESSURE, PREY, PUPA, QUEST, REACH,
    RUST, SCREAM, SHELL, SHIELD, SILVER, SHRED, SLEEP, SLEIGHT, SLIME, SLUMBER, SOOT, SOUL, SPARK, SPORE, STORAGE,
    STRIFE, STUDY, TASK, THEFT, TIDE, TIME, TOWER, TRAINING, TRAMPLE, TRAP, TREASURE, VELOCITY, VERSE, VIGILANCE,
    VITALITY, VOLATILE, WAGE, WINCH, WIND, WISH, TRIBUTE;
}
