package magic.logic.card.abilities.utils;

import magic.logic.utils.GameEvent;

public enum Event implements GameEvent {
	ATTACK,
	IS_DEALT_DAMAGE, DEALT_DAMAGE, DEALS_COMBAT_DAMAGE,
	
	BECOME_BLOCKED, BLOCKS,
	
	ENTER_BATTLEFIELD, 
	CAST, ABILITIES, TARGET,
	
	ADDED_COUNTER, REMOVED_COUNTER,
	TAPPED, UNTAPPED,
	SACRIFICE, DIES, DESTROY,
	CREATE_TOKEN,
	
	EQUIP, ENCHANT, UNATTACHED,
	
	PUT_INTO_GRAVEYARD, PUT_INTO_EXILE, PUT_INTO_LIBRARY, PUT_INTO_HAND, RETURNED_INTO_HAND,
	
	GAIN_LIFE, LOSE_LIFE,
	DRAW_CARD, DISCARD_CARD, SCRY,
	ADD_MANA, SPEND_MANA;
}
