package magic.logic.card;

public enum CreatureT {

	CHANGELING,
	ADVISOR, AETHERBORN, ALICORN, ALIEN, ALLY, ANGEL, ANTELOPE, APE, ARCHER, ARCHON, ARMY, ART, ARTIFICER, ASSASSIN,
	ASSEMBLY_WORKER, ATOG, AUROCHS, AUTOBOT, AVATAR, AZRA, BADDEST, BADGER, BARBARIAN, BASILISK, BAT, BEAR, BEAST,
	BEAVER, BEEBLE, BEHOLDER, BERSERKER, BIGGEST, BIRD, BLINKMOTH, BOAR, BRAINIAC, BRINGER, BRUSHWAGG, BUREAUCRAT,
	CAMARID, CAMEL, CARIBOU, CARRIER, CAT, CENTAUR, CEPHALID, CHAMELEON, CHICKEN, CHILD, CHIMERA, CITIZEN, CLAMFOLK,
	CLERIC, COCKATRICE, CONSTRUCT, COW, COWARD, CRAB, CROCODILE, CYBORG, CYCLOPS, DAUTHI, DEER, DEMIGOD, DEMON,
	DESERTER, DESIGNER, DEVIL, DINOSAUR, DJINN, DOG, DONKEY, DRAGON, DRAKE, DREADNOUGHT, DRONE, DRUID, DRYAD, DWARF,
	EFREET, EGG, ELDER, ELDRAZI, ELEMENTAL, ELEPHANT, ELF, ELK, ELVES, ETIQUETTE, EYE, FAERIE, FERRET, FISH, FLAGBEARER,
	FOX, FRACTAL, FROG, FUNGUS, GAMER, GARGOYLE, GERM, GIANT, GNOME, GOAT, GOBLIN, GOD, GOLEM, GORGON, GRANDCHILD, GRAVEBORN,
	GREMLIN, GRIFFIN, GUS, HAG, HARPY, HATIFICER, HEAD, HELLION, HERO, HIPPO, HIPPOGRIFF, HOMARID, HOMUNCULUS, HORNET,
	HORROR, HORSE, HUMAN, HYDRA, HYENA, ILLUSION, IMP, INCARNATION, INSECT, ISLAND, JACKAL, JELLYFISH, JUGGERNAUT,
	KANGAROO, KAVU, KILLBOT, KIRIN, KITHKIN, KNIGHT, KOBOLD, KOR, KRAKEN, LADY, LAMIA, LAMMASU, LEECH, LEVIATHAN,
	LHURGOYF, LICID, LIZARD, LOBSTER, LOCUS, MAMMOTH, MANTICORE, MASTICORE, MERCENARY, MERFOLK, METATHRAN, MIME, MINION,
	MINOTAUR, MOLE, MONGER, MONGOOSE, MONK, MONKEY, MOONFOLK, MOUSE, MUMMY, MUTANT, MYR, MYSTIC, NAGA, NASTIEST,
	NAUTILUS, NEPHILIM, NIGHTMARE, NIGHTSTALKER, NINJA, NOBLE, NOGGLE, NOMAD, NYMPH, OCTOPUS, OGRE, OOZE, ORB, ORC,
	ORGG, OTTER, OUPHE, OX, OYSTER, PANGOLIN, PARATROOPER, PEASANT, PEGASUS, PENTAVITE, PEST, PHELDDAGRIF, PHOENIX,
	PHYREXIAN, PILOT, PINCHER, PIRATE, PLANT, PRAETOR, PRISM, PROCESSOR, PROPER, RABBIT, RACCOON, RAT, REBEL,
	REFLECTION, REVELER, RHINO, RIGGER, ROGUE, RUKH, SABLE, SALAMANDER, SAMURAI, SAND, SAPROLING, SATYR, SCARECROW,
	SCIENTIST, SCION, SCORPION, SCOUT, SCULPTURE, SERF, SERPENT, SERVO, SHADE, SHAMAN, SHAPESHIFTER, SHARK, SHEEP, SHIP,
	SIREN, SKELETON, SLITH, SLIVER, SLUG, SNAKE, SOLDIER, SOLTARI, SPAWN, SPECTER, SPELLSHAPER, SPHINX, SPIDER, SPIKE,
	SPIRIT, SPLINTER, SPONGE, SPY, SQUID, SQUIRREL, STARFISH, SURRAKAR, SURVIVOR, TEDDY, TENTACLE, TETRAVITE, THALAKOS,
	THE, THOPTER, THRULL, TOWNSFOLK, TREEFOLK, TRILOBITE, TRISKELAVITE, TROLL, TURTLE, UNICORN, VAMPIRE, VAMPYRE,
	VEDALKEN, VIASHINO, VILLAIN, VOLVER, WAITER, WALL, WARLOCK, WARRIOR, WASP, WEIRD, WEREWOLF, WHALE, WIZARD, WOLF,
	WOLVERINE, WOMBAT, WORM, WRAITH, WRESTLER, WURM, YETI, ZOMBIE, ZUBERA;
	
	public String getName() {
		return this.name();
	}
}
