package magic.logic.card;

/**
 * All The different planeswalker of mtg
 */
public enum PT {
	ABIAN, AJANI, AMINATOU, ANGRATH, ARLINN, ASHIOK, B_O_B, BASRI, BOLAS, CALIX, CHANDRA, DACK, DARETTI, DAVRIEL, DOMRI,
	DOVIN, DUCK, DUNGEON, ELSPETH, ESTRID, FREYALISE, GARRUK, GIDEON, HUATLI, INZERVA, JACE, JAYA, KARN, KASMINA, KAYA,
	KIORA, KOTH, LILIANA, LUKKA, MASTER, NAHIRI, NARSET, NISSA, NIXILIS, OKO, RAL, ROWAN, SAHEELI, SAMUT, SARKHAN,
	SERRA, SORIN, TAMIYO, TEFERI, TEYO, TEZZERET, TIBALT, UGIN, URZA, VENSER, VIVIEN, VRASKA, WILL, WINDGRACE, WRENN,
	XENAGOS, YANGGU, YANLING;
}
